"""《画堂春》完整剧本 JSON"""
from app.models import (
    StoryScript, StoryMeta, StoryNode, RoleProfile,
    Segment, Choice, RouteCondition,
    InputMode, SpeakerType
)

HUATANGCHUN_WENTANG = StoryScript(
    meta=StoryMeta(
        story_id="huatangchun_wentang",
        title="画堂春",
        author="鸠森",
        source_url="https://www.zhihu.com/market/paid_column/1725479677609644032/section/1935677831142171296",
        genre="古言",
        world_setting="架空封建王朝后宫，皇权至上，等级森严。后宫争宠夺权与皇子抚育权争夺是核心冲突。",
        max_players=5,
        min_players=1,
        roles=[
            RoleProfile(
                role_id="wentang",
                name="温棠",
                identity="温贵人，入宫十年，四皇子生母",
                personality="温和隐忍，善良心软，不争不抢，胆小求稳",
                speaking_style="语气温和，偶尔结巴，对皇帝恭敬，对裴琰温柔",
                core_purpose="活下去，守护孩子，弥补对两个孩子的亏欠",
                trigger_points=["制作枣花糕", "缝补衣物", "试图接近裴瑜", "保护裴琰"],
                weakness="心软，胆小，对裴瑜的执念",
                playable=True,
                required=True,
                avatar_prompt="温婉女子，素衣淡妆，眉眼柔和，手中握着枣花糕",
            ),
            RoleProfile(
                role_id="peirong",
                name="裴容",
                identity="大胤皇帝，后宫与朝堂的绝对主宰",
                personality="喜怒不形于色，理性凉薄，皇权至上，看重温顺贤德",
                speaking_style="语气平淡沉稳，带帝王威严，说话简洁偶尔反问",
                core_purpose="平衡后宫势力，妥善安置皇子，维持统治稳定",
                trigger_points=["翻牌子", "视察各宫", "询问皇子近况"],
                weakness="对安宁纯粹的氛围没抵抗力，念旧情",
                playable=True,
                required=False,
                avatar_prompt="帝王装扮，面容冷峻，龙袍手持书卷，喜怒不形于色",
            ),
            RoleProfile(
                role_id="peiyan",
                name="裴琰",
                identity="三皇子，废贵妃之子，9岁",
                personality="早熟隐忍，敏感懂事，察言观色极强，知恩图报",
                speaking_style="语气乖巧小心翼翼，对温棠温柔依赖，紧张时磕巴",
                core_purpose="报答温棠，帮温棠争宠，保护温棠",
                trigger_points=["接受枣花糕", "帮温棠出主意", "被裴瑜欺负"],
                weakness="内心敏感，害怕被抛弃，面对强势者本能退缩",
                playable=True,
                required=False,
                avatar_prompt="瘦弱少年，面色苍白，衣着朴素，眼神早熟却藏着温顺",
            ),
            RoleProfile(
                role_id="peiyu",
                name="裴瑜",
                identity="四皇子，温棠亲生儿子，皇后养子，8岁",
                personality="骄纵傲慢，趋炎附势，自私自利，看不起低位者",
                speaking_style="语气骄纵偏快带傲气，对温棠轻蔑，对皇后撒娇",
                core_purpose="获得皇后宠爱，彰显优越感",
                trigger_points=["欺负裴琰", "嘲讽温棠", "向皇后撒娇"],
                weakness="过于依赖皇后，内心深处渴望母爱",
                playable=True,
                required=False,
                avatar_prompt="锦衣少年，面容娇俏，眼神骄纵，身着华贵服饰",
            ),
            RoleProfile(
                role_id="chenmomo",
                name="陈嬷嬷",
                identity="温棠同乡，温棠贴身嬷嬷",
                personality="慈心善良，通透世故，深谙后宫生存之道",
                speaking_style="语气温和平缓，对温棠真诚直白，对皇帝皇后不卑不亢",
                core_purpose="保护温棠不受伤害，看着温棠获得好结局",
                trigger_points=["给温棠提建议", "提醒温棠避祸", "安慰失意的温棠"],
                weakness="过于在意温棠，容易因温棠安危乱了分寸",
                playable=True,
                required=False,
                avatar_prompt="年长嬷嬷，衣着朴素，面容慈祥，眼神通透",
            ),
        ],
        start_node_id="act1_start",
    ),
    nodes={
        # ─── 第一幕：雪夜承宠 ───
        "act1_start": StoryNode(
            node_id="act1_start",
            act=1,
            act_title="第一幕 · 雪夜承宠",
            scene_name="采桑宫偏殿",
            scene_description="夜深了，窗外雪落无声，采桑宫的灯火难得点着。",
            ambient="静谧",
            progress=5,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="入宫十年，温棠早已习惯了被遗忘的滋味。今夜，窗外雪落无声，采桑宫偏殿里，她独自坐着，手边摆着一碟枣花糕——这是她唯一拿得出手的东西。",
                        input_mode=InputMode.NARRATION),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="贵人，仇公公来了，说……说陛下今夜要翻您的牌子。",
                        input_mode=InputMode.FIXED, emotion_tag="惊讶"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="听到这消息，你心里……",
                        input_mode=InputMode.GUIDED,
                        guided_options=["惊喜，连忙整理仪容", "惊慌，不知所措", "平静，这只是意外"]),
            ],
            choices=[
                Choice(text="惊喜，连忙整理仪容", next="act1_arrive_emperor",
                       changes={"val": 5, "wentang_peirong": 5},
                       influence_hint="皇帝注意到你的慌乱与真诚"),
                Choice(text="惊慌，不知所措", next="act1_arrive_emperor",
                       changes={"val": 0},
                       influence_hint="皇帝感受到了你的紧张"),
                Choice(text="平静，这只是意外", next="act1_arrive_emperor",
                       changes={"val": -5, "wentang_peirong": 2},
                       influence_hint="皇帝对你的淡然有些意外"),
            ],
        ),

        "act1_arrive_emperor": StoryNode(
            node_id="act1_arrive_emperor",
            act=1,
            scene_name="采桑宫偏殿",
            scene_description="皇帝驾临，采桑宫偏殿灯火通明。",
            progress=15,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴容步入采桑宫，目光扫过简陋的陈设，在那碟枣花糕上停了一瞬。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕记得，你入宫时带了一手做枣花糕的本事。",
                        input_mode=InputMode.FIXED, emotion_tag="平淡"),
            ],
            choices=[
                Choice(text="「臣妾做的不好，让陛下见笑了。」", next="act1_peiyan_question",
                       changes={"val": 5, "wentang_peirong": 8},
                       influence_hint="皇帝对你的谦逊印象不错"),
                Choice(text="「陛下还记得？臣妾……臣妾很高兴。」", next="act1_peiyan_question",
                       changes={"val": 8, "wentang_peirong": 12},
                       influence_hint="真情流露，皇帝眼神柔和了一瞬"),
                Choice(text="「臣妾备了红豆甜汤，陛下可要尝尝？」", next="act1_peiyan_question",
                       changes={"val": 3, "wentang_peirong": 6},
                       influence_hint="皇帝接过汤，沉默地喝了一口"),
            ],
        ),

        "act1_peiyan_question": StoryNode(
            node_id="act1_peiyan_question",
            act=1,
            scene_name="采桑宫偏殿",
            progress=30,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕问你，三皇子琰儿如今无人抚育，你……可愿接手？",
                        input_mode=InputMode.FIXED, emotion_tag="观察"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="这是一道难题。抚育失势皇子，是祸是福，无人说得清。"),
            ],
            choices=[
                Choice(text="「臣妾愿悉心照料琰儿。」", next="act1_peiyan_accept",
                       changes={"wentang_peirong": 10, "wentang_peiyan": 15, "addFlag": "accepted_peiyan"},
                       influence_hint="裴容亲密度+10，裴琰亲密度+15，解锁剧情「采桑宫温居」"),
                Choice(text="「陛下，琰儿乃皇子，臣妾恐难当此任……」", next="act1_peiyan_hesitate",
                       changes={"wentang_peirong": 5, "wentang_peiyan": 5},
                       influence_hint="皇帝目光变得沉沉的"),
                Choice(text="「臣妾只想盼着瑜儿回心转意……」", next="act1_peiyan_refuse",
                       changes={"wentang_peirong": -5, "wentang_peiyu": 5, "addFlag": "refused_peiyan"},
                       influence_hint="皇帝沉默了很久"),
            ],
        ),

        "act1_peiyan_accept": StoryNode(
            node_id="act1_peiyan_accept",
            act=1,
            scene_name="采桑宫偏殿",
            progress=45,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="好。明日圣旨下达，琰儿便送入采桑宫。",
                        emotion_tag="满意"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="他走了，留下一室安静。你握着那碟枣花糕，不知这是幸还是不幸。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="🎉 解锁「采桑宫温居」支线！第一幕完成。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_start")],
        ),

        "act1_peiyan_hesitate": StoryNode(
            node_id="act1_peiyan_hesitate",
            act=1,
            scene_name="采桑宫偏殿",
            progress=40,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="你害怕什么？",
                        emotion_tag="审视"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act1_peiyan_accept")],
        ),

        "act1_peiyan_refuse": StoryNode(
            node_id="act1_peiyan_refuse",
            act=1,
            scene_name="采桑宫偏殿",
            progress=35,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="……罢了。",
                        emotion_tag="冷淡"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="皇帝对你的印象有所下降。裴琰仍无人抚育……",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_start_no_peiyan")],
        ),

        # ─── 第二幕：抚育之诺 ───
        "act2_start": StoryNode(
            node_id="act2_start",
            act=2,
            act_title="第二幕 · 抚育之诺",
            scene_name="采桑宫正殿",
            scene_description="次日清晨，圣旨下达。裴琰站在采桑宫门口，瘦弱的身影让温棠心疼。",
            ambient="清晨",
            progress=50,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="圣旨下了。裴琰被送来采桑宫——一个瘦弱的孩子，眼神里藏着远超年龄的戒备。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……您就是温贵人？",
                        input_mode=InputMode.FIXED, emotion_tag="戒备"),
            ],
            choices=[
                Choice(text="「是我。以后这里就是你的家。」", next="act2_warmth",
                       changes={"wentang_peiyan": 20, "val": 5, "addFlag": "warm_welcome"},
                       influence_hint="裴琰愣了一下，眼眶微红"),
                Choice(text="「你饿了吗？我做了枣花糕。」", next="act2_cake",
                       changes={"wentang_peiyan": 15, "val": 3},
                       influence_hint="裴琰看着那碟糕点，攥紧了衣角"),
                Choice(text="先打量他，沉默片刻再开口", next="act2_silent",
                       changes={"wentang_peiyan": 5},
                       influence_hint="孩子的戒备没有消散"),
            ],
        ),

        "act2_warmth": StoryNode(
            node_id="act2_warmth",
            act=2,
            scene_name="采桑宫正殿",
            progress=60,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……您不怕抚育我会惹祸？",
                        emotion_tag="困惑又期待"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act2_peiyu_bully")],
        ),

        "act2_cake": StoryNode(
            node_id="act2_cake",
            act=2,
            scene_name="采桑宫正殿",
            progress=58,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（沉默地接过，小口咬了一口）……甜的。",
                        emotion_tag="戒备渐消"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="裴琰信任值 +8",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_peiyu_bully")],
        ),

        "act2_silent": StoryNode(
            node_id="act2_silent",
            act=2,
            scene_name="采桑宫正殿",
            progress=55,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（低头，不再说话）",
                        emotion_tag="失落"),
            ],
            routes=[RouteCondition(condition="default", next="act2_bond")],
        ),


        # ─── 第二幕：冲突节点 ───
        "act2_peiyu_bully": StoryNode(
            node_id="act2_peiyu_bully",
            act=2,
            scene_name="采桑宫院子",
            scene_description="裴瑜带着几个小太监闯入采桑宫，看到裴琰时，眼里满是轻蔑。",
            progress=62,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="第三天，麻烦来了。裴瑜不知从哪听说了裴琰被送到采桑宫的消息。"),
                Segment(speaker="裴瑜", speaker_type=SpeakerType.BOT,
                        text="哟，废妃的崽子，在这吃得挺好嘛。这枣花糕也配你吃？",
                        input_mode=InputMode.FIXED, emotion_tag="嘲讽"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（裴琰攥紧拳头，低着头一言不发。）",
                        emotion_tag="隐忍"),
            ],
            choices=[
                Choice(text="挡在裴琰面前：「四殿下，采桑宫不欢迎不请自来的客人。」",
                       next="act2_protect_peiyan",
                       changes={"val": 10, "wentang_peiyan": 20, "wentang_peiyu": -10, "addFlag": "protected_peiyan"},
                       influence_hint="裴琰眼眶泛红，裴瑜气得跺脚"),
                Choice(text="假装没看见，低头继续做针线",
                       next="act2_bond",
                       changes={"wentang_peiyan": -5},
                       influence_hint="裴琰的眼神暗了下去"),
                Choice(text="赔笑脸：「四殿下来了？快坐，臣妾给你做点心。」",
                       next="act2_bond",
                       changes={"wentang_peiyu": 5, "wentang_peiyan": -10},
                       influence_hint="裴琰安静地退到了角落"),
            ],
        ),

        "act2_protect_peiyan": StoryNode(
            node_id="act2_protect_peiyan",
            act=2,
            scene_name="采桑宫院子",
            progress=65,
            segments=[
                Segment(speaker="裴瑜", speaker_type=SpeakerType.BOT,
                        text="你——你算什么东西！我可是皇后娘娘养大的！",
                        emotion_tag="气急败坏"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴瑜甩袖而去，身后的小太监们慌忙跟上。你感到一只小手悄悄攥住了你的衣角。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……母妃，你不怕他去告状吗？",
                        emotion_tag="担忧又感动"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act2_empress_warning")],
        ),

        "act2_empress_warning": StoryNode(
            node_id="act2_empress_warning",
            act=2,
            scene_name="采桑宫正殿",
            scene_description="傍晚，皇后身边的仇公公带来了一道口谕。",
            progress=68,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="果然，傍晚时分，仇公公就来了。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="【剧情背景】仇公公是皇后的心腹，在宫中人人避之不及。他的出现意味着皇后已经知道了今天的事。",
                        card_type="当前线索"),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="（低声）贵人，来者不善。您千万别硬顶，先忍一忍。",
                        emotion_tag="紧张"),
            ],
            choices=[
                Choice(text="恭敬接旨，不做辩解",
                       next="act2_bond",
                       changes={"val": -5, "addFlag": "empress_warned"},
                       influence_hint="皇后暂时没有更多动作，但你知道她在看着"),
                Choice(text="委婉解释：「臣妾只是照顾陛下交代的孩子……」",
                       next="act2_bond",
                       changes={"val": 5, "wentang_peirong": 5, "addFlag": "used_emperor_shield"},
                       influence_hint="搬出皇帝，仇公公脸色变了变"),
            ],
        ),

        "act2_bond": StoryNode(
            node_id="act2_bond",
            act=2,
            scene_name="采桑宫正殿",
            progress=70,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="日子就这样过去了。裴琰开始帮你理账，帮你在皇帝面前说好话，用一个九岁孩子所能做的一切，偿还着你的善意。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="母妃，我听说陛下喜欢喝红豆甜汤……您做得最好喝了，要不要让我帮您送过去？",
                        emotion_tag="认真"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="🔗 裴琰主动帮温棠争宠，裴琰信任值大幅提升",
                        card_type="当前线索"),
            ],
            choices=[
                Choice(text="「你有这份心，母妃很高兴。」", next="act3_start",
                       changes={"wentang_peiyan": 15, "val": 5, "addFlag": "peiyan_help"},
                       influence_hint="裴琰眼睛亮了"),
                Choice(text="「不用，你还小，别掺和这些。」", next="act3_start",
                       changes={"wentang_peiyan": 5},
                       influence_hint="裴琰有些失落，但点了点头"),
            ],
        ),

        "act2_start_no_peiyan": StoryNode(
            node_id="act2_start_no_peiyan",
            act=2,
            act_title="第二幕 · 孤立无援",
            scene_name="采桑宫",
            progress=50,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="没有裴琰，采桑宫更冷清了。皇帝的翻牌也越来越少……"),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="贵人，您真的不考虑重新请求陛下，把琰儿接来吗？",
                        emotion_tag="担忧"),
            ],
            choices=[
                Choice(text="「嬷嬷说得对，我去试试。」", next="act2_start",
                       changes={"addFlag": "accepted_peiyan", "wentang_peirong": -5}),
                Choice(text="「算了，我命如此。」", next="act3_bad_ending_route"),
            ],
        ),

        # ─── 第三幕：帝临采桑 ───
        "act3_start": StoryNode(
            node_id="act3_start",
            act=3,
            act_title="第三幕 · 帝临采桑",
            scene_name="采桑宫",
            scene_description="某日，皇帝驾临采桑宫。这一次，不是翻牌子，而是……",
            ambient="悬念",
            progress=80,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴容再次踏入采桑宫，目光在温棠与裴琰之间流转了一瞬。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕听说……这孩子近来颇为懂事。",
                        emotion_tag="审视"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（悄悄拉了拉温棠的袖子，小声道）……母妃，红豆甜汤。",
                        emotion_tag="提醒"),
            ],
            choices=[
                Choice(text="立刻呈上红豆甜汤", next="act3_good_route",
                       changes={"wentang_peirong": 15, "val": 8, "addFlag": "sweet_soup_offered"},
                       influence_hint="皇帝接过，眼中有什么闪过"),
                Choice(text="先问皇帝今日来意", next="act3_ask_route",
                       changes={"wentang_peirong": 5},
                       influence_hint="皇帝对你的谨慎略感意外"),
                Choice(text="让裴琰亲手呈上", next="act3_peiyan_route",
                       changes={"wentang_peirong": 10, "wentang_peiyan": 10, "addFlag": "peiyan_served"},
                       influence_hint="皇帝看着裴琰，沉默良久"),
            ],
        ),

        "act3_good_route": StoryNode(
            node_id="act3_good_route",
            act=3,
            scene_name="采桑宫",
            progress=88,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="（喝了一口，沉默）……朕有意晋你为妃。",
                        emotion_tag="平静却有重量"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="这句话落在心里，温棠久久说不出话来。"),
            ],
            routes=[
                RouteCondition(condition="hasFlag 'peiyan_help'", next="ending_true"),
                RouteCondition(condition="default", next="ending_normal"),
            ],
        ),

        "act3_ask_route": StoryNode(
            node_id="act3_ask_route",
            act=3,
            scene_name="采桑宫",
            progress=85,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="来看看这孩子，也看看你。",
                        emotion_tag="淡淡的"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act3_good_route")],
        ),

        "act3_peiyan_route": StoryNode(
            node_id="act3_peiyan_route",
            act=3,
            scene_name="采桑宫",
            progress=88,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（双手捧上，声音稳稳的）陛下，这是母妃亲手做的红豆甜汤，说陛下喜欢。",
                        emotion_tag="认真"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="（接过，看着裴琰，久久不语）……",
                        emotion_tag="复杂"),
            ],
            routes=[RouteCondition(condition="default", next="ending_true")],
        ),

        "act3_bad_ending_route": StoryNode(
            node_id="act3_bad_ending_route",
            act=3,
            scene_name="采桑宫",
            progress=80,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="没有裴琰的日子，采桑宫越来越冷清。皇帝的翻牌彻底消失了……"),
            ],
            routes=[RouteCondition(condition="default", next="ending_bad")],
        ),

        # ─── 结局 ───
        "ending_true": StoryNode(
            node_id="ending_true",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="温暖",
            is_ending=True,
            ending_type="圆满",
            ending_title="结局·采桑宫春",
            ending_description="温棠封妃，裴琰健康成长，在采桑宫这片小小的净土里，终于有了真正意义上的家。皇帝的目光越来越多地落在采桑宫，不只是因为那碗红豆甜汤，更是因为这里有种久违的安宁。",
            ending_closing="后来裴琰常说，是母妃教会了他，善意不需要回报，但它永远不会白费。",
        ),

        "ending_normal": StoryNode(
            node_id="ending_normal",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="平静",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·岁月静好",
            ending_description="温棠晋了位份，日子稳稳当当地过着。裴琰长大了，偶尔还是会来采桑宫蹭枣花糕。只是那碗红豆甜汤后来皇帝再没提起，仿佛只是寻常一日。",
            ending_closing="温棠后来想，也许平静本身，就是这深宫里最难得的好结局。",
        ),

        "ending_bad": StoryNode(
            node_id="ending_bad",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="萧索",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·一盏残灯",
            ending_description="没有裴琰，没有皇帝的眷顾，温棠在采桑宫的灯火越烧越暗。她仍旧做着枣花糕，只是再没有人来吃了。",
            ending_closing="有些错过，一旦发生，就真的过去了。",
        ),
    },
)


# ════════════════════════════════════════════════════════════════════════
# 《画堂春》—— 裴容视角（主角：裴容）
# 同一时间线，皇帝视角经历雪夜翻牌、托付琰儿、宫廷角力
# ════════════════════════════════════════════════════════════════════════

HUATANGCHUN_PEIRONG = StoryScript(
    meta=StoryMeta(
        story_id="huatangchun_peirong",
        title="画堂春·天子篇",
        author="鸠森",
        source_url="https://www.zhihu.com/market/paid_column/1725479677609644032/section/1935677831142171296",
        genre="古言",
        world_setting="架空封建王朝后宫，皇权至上，等级森严。后宫争宠夺权与皇子抚育权争夺是核心冲突。",
        max_players=5,
        min_players=1,
        roles=[
            RoleProfile(
                role_id="peirong",
                name="裴容",
                identity="大胤皇帝，后宫与朝堂的绝对主宰",
                personality="喜怒不形于色，理性凉薄，皇权至上，看重温顺贤德",
                speaking_style="语气平淡沉稳，带帝王威严，说话简洁偶尔反问",
                core_purpose="平衡后宫势力，妥善安置皇子，维持统治稳定",
                trigger_points=["翻牌子", "视察各宫", "询问皇子近况"],
                weakness="对安宁纯粹的氛围没抵抗力，念旧情",
                playable=True,
                required=True,
                avatar_prompt="帝王装扮，面容冷峻，龙袍手持书卷，喜怒不形于色",
            ),
            RoleProfile(
                role_id="wentang",
                name="温棠",
                identity="温贵人，入宫十年，四皇子生母",
                personality="温和隐忍，善良心软，不争不抢，胆小求稳",
                speaking_style="语气温和，偶尔结巴，对皇帝恭敬，对裴琰温柔",
                core_purpose="活下去，守护孩子，弥补对两个孩子的亏欠",
                trigger_points=["制作枣花糕", "缝补衣物", "试图接近裴瑜", "保护裴琰"],
                weakness="心软，胆小，对裴瑜的执念",
                playable=True,
                required=False,
                avatar_prompt="温婉女子，素衣淡妆，眉眼柔和，手中握着枣花糕",
            ),
            RoleProfile(
                role_id="peiyan",
                name="裴琰",
                identity="三皇子，废贵妃之子，9岁",
                personality="早熟隐忍，敏感懂事，察言观色极强，知恩图报",
                speaking_style="语气乖巧小心翼翼，对温棠温柔依赖，紧张时磕巴",
                core_purpose="报答温棠，帮温棠争宠，保护温棠",
                trigger_points=["接受枣花糕", "帮温棠出主意", "被裴瑜欺负"],
                weakness="内心敏感，害怕被抛弃，面对强势者本能退缩",
                playable=True,
                required=False,
                avatar_prompt="瘦弱少年，面色苍白，衣着朴素，眼神早熟却藏着温顺",
            ),
            RoleProfile(
                role_id="peiyu",
                name="裴瑜",
                identity="四皇子，温棠亲生儿子，皇后养子，8岁",
                personality="骄纵傲慢，趋炎附势，自私自利，看不起低位者",
                speaking_style="语气骄纵偏快带傲气，对温棠轻蔑，对皇后撒娇",
                core_purpose="获得皇后宠爱，彰显优越感",
                trigger_points=["欺负裴琰", "嘲讽温棠", "向皇后撒娇"],
                weakness="过于依赖皇后，内心深处渴望母爱",
                playable=True,
                required=False,
                avatar_prompt="锦衣少年，面容娇俏，眼神骄纵，身着华贵服饰",
            ),
            RoleProfile(
                role_id="chenmomo",
                name="陈嬷嬷",
                identity="温棠同乡，温棠贴身嬷嬷",
                personality="慈心善良，通透世故，深谙后宫生存之道",
                speaking_style="语气温和平缓，对温棠真诚直白，对皇帝皇后不卑不亢",
                core_purpose="保护温棠不受伤害，看着温棠获得好结局",
                trigger_points=["给温棠提建议", "提醒温棠避祸", "安慰失意的温棠"],
                weakness="过于在意温棠，容易因温棠安危乱了分寸",
                playable=True,
                required=False,
                avatar_prompt="年长嬷嬷，衣着朴素，面容慈祥，眼神通透",
            ),
        ],
        start_node_id="p_act1_start",
    ),
    nodes={
        # ─── 第一幕：雪夜翻牌 ───
        "p_act1_start": StoryNode(
            node_id="p_act1_start",
            act=1,
            act_title="第一幕 · 雪夜翻牌",
            scene_name="御书房",
            scene_description="夜深了，窗外雪落无声。仇公公捧着牌子进来，等待天子翻牌。",
            ambient="肃静",
            progress=5,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="夜批奏折，案头堆积如山。仇公公无声地立在一旁，那盘牌子已经等了一个时辰。你搁笔，目光扫过去——采桑宫，温棠。",
                        input_mode=InputMode.NARRATION),
                Segment(speaker="仇公公", speaker_type=SpeakerType.BOT,
                        text="陛下，今夜可要翻牌子？",
                        input_mode=InputMode.FIXED, emotion_tag="恭敬"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="你盯着那块牌子，心里……",
                        input_mode=InputMode.GUIDED,
                        guided_options=["翻她的牌。许久未见，想看看了。", "随手翻过，无甚特别。", "原本要放下，却鬼使神差翻了她的。"]),
            ],
            choices=[
                Choice(text="翻她的牌。许久未见，想看看了。",
                       next="p_act1_arrive",
                       changes={"val": 8, "peirong_wentang": 10},
                       influence_hint="你主动记挂着采桑宫"),
                Choice(text="随手翻过，无甚特别。",
                       next="p_act1_arrive",
                       changes={"val": 3, "peirong_wentang": 3},
                       influence_hint="随机之下，缘分自有安排"),
                Choice(text="原本要放下，却鬼使神差翻了她的。",
                       next="p_act1_arrive",
                       changes={"val": 5, "peirong_wentang": 6, "addFlag": "p_unexplained_pull"},
                       influence_hint="连你自己也说不清这一念"),
            ],
        ),

        "p_act1_arrive": StoryNode(
            node_id="p_act1_arrive",
            act=1,
            scene_name="采桑宫偏殿",
            scene_description="采桑宫灯火骤亮，陈设简朴，案上摆着一碟枣花糕。",
            progress=15,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="采桑宫比你记忆里还要简陋几分。温棠匆忙起身行礼，发间钗饰松了，她浑然未觉。案上那碟枣花糕的香气，却是久违的熟悉。"),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="臣妾……臣妾参见陛下。",
                        input_mode=InputMode.FIXED, emotion_tag="惊慌"),
            ],
            choices=[
                Choice(text="「免礼。那碟枣花糕，是你做的？」",
                       next="p_act1_cake_talk",
                       changes={"val": 5, "peirong_wentang": 10},
                       influence_hint="温棠愣了一下，没想到你记得"),
                Choice(text="径直落座，不发一言，只看着她。",
                       next="p_act1_silent_observe",
                       changes={"val": 3, "peirong_wentang": 5},
                       influence_hint="沉默本身也是一种审视"),
                Choice(text="「多少年没来了。采桑宫……还好？」",
                       next="p_act1_gentle_ask",
                       changes={"val": 8, "peirong_wentang": 12, "addFlag": "p_emperor_showed_care"},
                       influence_hint="温棠眼眶微动，随即低下头"),
            ],
        ),

        "p_act1_cake_talk": StoryNode(
            node_id="p_act1_cake_talk",
            act=1,
            scene_name="采桑宫偏殿",
            progress=22,
            segments=[
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="是……是臣妾做的，臣妾入宫时就会，只怕做得粗陋……",
                        emotion_tag="局促"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="你拈起一块，咬了口。甜而不腻，带着些许木樨香。说不清是糕好，还是这一室安静让你放松了。"),
            ],
            routes=[RouteCondition(condition="default", next="p_act1_peiyan_decision")],
        ),

        "p_act1_silent_observe": StoryNode(
            node_id="p_act1_silent_observe",
            act=1,
            scene_name="采桑宫偏殿",
            progress=18,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="她站着，手不知往哪放，只是垂着眼，安静地等。这种不争不辩的姿态，在这后宫里反而少见。"),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="……陛下可要用些点心？臣妾备了红豆甜汤。",
                        emotion_tag="小心翼翼"),
            ],
            routes=[RouteCondition(condition="default", next="p_act1_peiyan_decision")],
        ),

        "p_act1_gentle_ask": StoryNode(
            node_id="p_act1_gentle_ask",
            act=1,
            scene_name="采桑宫偏殿",
            progress=20,
            segments=[
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="（声音微哽）……臣妾都好，陈嬷嬷照顾得周到。陛下……还记得采桑宫。",
                        emotion_tag="感动压抑"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="p_act1_peiyan_decision")],
        ),

        "p_act1_peiyan_decision": StoryNode(
            node_id="p_act1_peiyan_decision",
            act=1,
            scene_name="采桑宫偏殿",
            progress=32,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="话说到一半，你想起正事——三皇子琰儿，生母被废，无人抚育，朝中已有言官上折。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="你打量着温棠，心里权衡着……",
                        input_mode=InputMode.GUIDED,
                        guided_options=["此女温顺，交给她最省心", "托付皇子是大事，还需再观察", "琰儿可怜，她若真心抚育，也算一桩善事"]),
            ],
            choices=[
                Choice(text="此女温顺，交给她最省心",
                       next="p_act1_entrust_peiyan",
                       changes={"val": 5, "peirong_wentang": 8, "addFlag": "p_rational_choice"},
                       influence_hint="政治逻辑驱动，稳妥"),
                Choice(text="托付皇子是大事，还需再观察",
                       next="p_act1_test_wentang",
                       changes={"val": 3, "peirong_wentang": 5},
                       influence_hint="你先出一道题"),
                Choice(text="琰儿可怜，她若真心抚育，也算一桩善事",
                       next="p_act1_entrust_peiyan",
                       changes={"val": 8, "peirong_wentang": 12, "peirong_peiyan": 10, "addFlag": "p_compassionate_choice"},
                       influence_hint="难得一见的柔软"),
            ],
        ),

        "p_act1_test_wentang": StoryNode(
            node_id="p_act1_test_wentang",
            act=1,
            scene_name="采桑宫偏殿",
            progress=36,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="「朕问你，若朕将一个无依无靠的孩子送来，你能护得住他吗？」",
                        input_mode=InputMode.FIXED),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="（沉默了一息，抬起眼）……臣妾护不了多少，但臣妾愿意护。",
                        emotion_tag="认真"),
            ],
            routes=[RouteCondition(condition="default", next="p_act1_entrust_peiyan")],
        ),

        "p_act1_entrust_peiyan": StoryNode(
            node_id="p_act1_entrust_peiyan",
            act=1,
            scene_name="采桑宫偏殿",
            progress=45,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="「明日圣旨下达，三皇子琰儿送入采桑宫，由你抚育。」",
                        input_mode=InputMode.FIXED),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="……是。臣妾领旨，定竭尽所能。",
                        emotion_tag="郑重"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="你离开采桑宫。夜雪还在下，你回头看了一眼那扇微亮的窗——说不清为何多看了一眼。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="🎉 琰儿托付采桑宫，第一幕完成。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="p_act2_start")],
        ),

        # ─── 第二幕：宫廷角力 ───
        "p_act2_start": StoryNode(
            node_id="p_act2_start",
            act=2,
            act_title="第二幕 · 宫廷角力",
            scene_name="御书房",
            scene_description="三日后，皇后递来请安折，言辞间隐约提及采桑宫之事。",
            ambient="暗流",
            progress=52,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="皇后的请安折措辞得体，却在最后一行提了一句：\"采桑宫偏僻，恐难抚育皇子……\"你搁下折子，思量片刻。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="【剧情背景】皇后已知晓琰儿被送往采桑宫，正试探你的态度。此刻的回应将决定温棠在后宫的处境。",
                        card_type="当前线索"),
            ],
            choices=[
                Choice(text="不作回应，留中不发——皇后自会掂量",
                       next="p_act2_empress_pressure",
                       changes={"val": 5, "addFlag": "p_silent_warning"},
                       influence_hint="皇后的试探被你无声化解"),
                Choice(text="批复：\"采桑宫之事，朕已定夺，勿需多言。\"",
                       next="p_act2_clear_stance",
                       changes={"val": 8, "peirong_wentang": 10, "addFlag": "p_protected_wentang"},
                       influence_hint="旗帜鲜明，温棠有了一把伞"),
                Choice(text="召皇后觐见，当面问清她的意思",
                       next="p_act2_empress_confront",
                       changes={"val": 3, "addFlag": "p_confronted_empress"},
                       influence_hint="你要亲自摸清皇后底牌"),
            ],
        ),

        "p_act2_empress_pressure": StoryNode(
            node_id="p_act2_empress_pressure",
            act=2,
            scene_name="凤仪宫",
            progress=58,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="数日后，皇后送来裴瑜，说是\"让四皇子来给父皇请安\"。裴瑜进门就嚷着：采桑宫的贱人欺负他。"),
                Segment(speaker="裴瑜", speaker_type=SpeakerType.BOT,
                        text="父皇！那个温贵人凶儿臣！儿臣去看废妃的崽子，她……她把儿臣赶出来了！",
                        emotion_tag="委屈撒娇"),
            ],
            choices=[
                Choice(text="「你去采桑宫做什么？好好跟皇后娘娘读书去。」",
                       next="p_act2_report",
                       changes={"peirong_peiyu": -5, "peirong_wentang": 8, "addFlag": "p_defended_wentang_indirectly"},
                       influence_hint="裴瑜愣了，皇后眼神微变"),
                Choice(text="「朕知道了。」不置可否，看裴瑜自己退下。",
                       next="p_act2_report",
                       changes={"val": 3},
                       influence_hint="模棱两可，皇后摸不准你的态度"),
                Choice(text="「召温棠来，朕要亲自问问。」",
                       next="p_act2_summon_wentang",
                       changes={"peirong_wentang": 5, "addFlag": "p_summoned_wentang"},
                       influence_hint="温棠被急召入御书房"),
            ],
        ),

        "p_act2_clear_stance": StoryNode(
            node_id="p_act2_clear_stance",
            act=2,
            scene_name="御书房",
            progress=58,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="批复下达后，仇公公悄悄来报：皇后娘娘看了折子，沉默了半盏茶，什么都没说。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="温棠暂时安全——皇后知道了你的态度，短期内不会轻举妄动。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="p_act2_report")],
        ),

        "p_act2_empress_confront": StoryNode(
            node_id="p_act2_empress_confront",
            act=2,
            scene_name="凤仪宫",
            progress=56,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="皇后来了，面色从容，字字珠玑，将一番担忧说得情真意切——无非是说温棠位份低，恐难担大任。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="p_act2_report")],
        ),

        "p_act2_summon_wentang": StoryNode(
            node_id="p_act2_summon_wentang",
            act=2,
            scene_name="御书房",
            progress=60,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="温棠来了。她跪得很直，把事情原原本本说了——裴瑜闯入，出言辱琰儿，她将人请出，并无逾矩。"),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="……臣妾知道此举冒犯了四殿下，若陛下要罚，臣妾领罚。但琰儿……琰儿受了委屈，臣妾不能不管。",
                        emotion_tag="坚定"),
            ],
            routes=[RouteCondition(condition="default", next="p_act2_report")],
        ),

        "p_act2_report": StoryNode(
            node_id="p_act2_report",
            act=2,
            scene_name="御书房",
            scene_description="数日后，暗卫传来采桑宫的消息。",
            progress=65,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="采桑宫消息传来：裴琰近日主动帮温棠整理账目，还在宫内传话说温贵人所做红豆甜汤最好喝。一个九岁的孩子，已学着回报恩情。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="【剧情背景】裴琰与温棠的关系正在形成，这孩子比你想的更懂事。",
                        card_type="当前线索"),
            ],
            choices=[
                Choice(text="心中微动，决定亲自去看看",
                       next="p_act2_visit",
                       changes={"val": 8, "peirong_wentang": 12, "peirong_peiyan": 8, "addFlag": "p_went_to_visit"},
                       influence_hint="你很少主动踏出那一步"),
                Choice(text="点头，吩咐内务府多拨些用度给采桑宫",
                       next="p_act2_provide",
                       changes={"val": 5, "peirong_wentang": 8},
                       influence_hint="实际的支持，也是一种态度"),
                Choice(text="搁置，继续批折子——后宫之事不必事事过问",
                       next="p_act2_neglect",
                       changes={"val": -3, "peirong_wentang": 2},
                       influence_hint="你选择了距离"),
            ],
        ),

        "p_act2_visit": StoryNode(
            node_id="p_act2_visit",
            act=2,
            scene_name="采桑宫",
            progress=70,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="采桑宫院子里，裴琰正帮温棠晒冬日存的药材。两人说着什么，温棠轻声笑了——你在宫门口站了一会儿，才走进去。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（急忙行礼，声音略微发抖）……父皇。",
                        emotion_tag="拘谨"),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="（跪下）臣妾参见陛下，陛下驾临，有失远迎……",
                        emotion_tag="慌乱"),
            ],
            choices=[
                Choice(text="「免礼。都坐。朕只是路过。」",
                       next="p_act3_start",
                       changes={"peirong_wentang": 10, "peirong_peiyan": 10, "addFlag": "p_casual_visit"},
                       influence_hint="\"路过\"二字，让温棠微微松了口气"),
                Choice(text="看着裴琰，沉默良久，说：「长大了。」",
                       next="p_act3_start",
                       changes={"peirong_peiyan": 15, "val": 5},
                       influence_hint="裴琰低头，掩住了眼眶"),
            ],
        ),

        "p_act2_provide": StoryNode(
            node_id="p_act2_provide",
            act=2,
            scene_name="御书房",
            progress=67,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="用度拨下去了。据说温棠收到时愣了很久，后来托陈嬷嬷进宫传话，说了四个字：\"谢陛下恩典\"。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="采桑宫条件改善，裴琰和温棠有了更好的生活。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="p_act3_start")],
        ),

        "p_act2_neglect": StoryNode(
            node_id="p_act2_neglect",
            act=2,
            scene_name="御书房",
            progress=63,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="折子批完，你忘了这件事。直到一个月后，暗卫再报：皇后又差人去采桑宫找了麻烦，温棠应对得颤颤巍巍，裴琰气得哭了。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="你的沉默给了皇后可乘之机。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="p_act3_start")],
        ),

        # ─── 第三幕：帝临采桑 ───
        "p_act3_start": StoryNode(
            node_id="p_act3_start",
            act=3,
            act_title="第三幕 · 帝临采桑",
            scene_name="采桑宫",
            scene_description="春日，你再次踏入采桑宫。这一次，是为了一件事——温棠的位份。",
            ambient="春和",
            progress=82,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="朝中有人上折，言温棠抚育皇子有功，可晋位份。你搁置了三日，今日亲自来了。"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="采桑宫的桃花开了，裴琰在树下读书，见到你，第一次没有发抖，只是站起来，认真地行了一礼。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="你看着这一切，心里……",
                        input_mode=InputMode.GUIDED,
                        guided_options=["这才是应有的样子", "不知为何，这里比任何地方都让你平静", "后宫能有片刻安宁，是她的功劳"]),
            ],
            choices=[
                Choice(text="这才是应有的样子",
                       next="p_act3_decree",
                       changes={"val": 5, "peirong_peiyan": 8},
                       influence_hint="你心中有了决定"),
                Choice(text="不知为何，这里比任何地方都让你平静",
                       next="p_act3_linger",
                       changes={"val": 8, "peirong_wentang": 15, "addFlag": "p_found_peace"},
                       influence_hint="你没有立刻开口，只是坐了下来"),
                Choice(text="后宫能有片刻安宁，是她的功劳",
                       next="p_act3_decree",
                       changes={"val": 6, "peirong_wentang": 10, "peirong_peiyan": 5},
                       influence_hint="你认可了温棠的付出"),
            ],
        ),

        "p_act3_linger": StoryNode(
            node_id="p_act3_linger",
            act=3,
            scene_name="采桑宫",
            progress=87,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="温棠端来红豆甜汤，也坐在一旁，没有多言。裴琰捧着书，偷偷瞄了你一眼，又低下头去。院子里只有风声和翻书声。"),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="……陛下，今日来，是有什么……",
                        emotion_tag="小心"),
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="p_act3_decree")],
        ),

        "p_act3_decree": StoryNode(
            node_id="p_act3_decree",
            act=3,
            scene_name="采桑宫",
            progress=92,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.PLAYER,
                        text="「朕有意晋你为妃。」",
                        input_mode=InputMode.FIXED),
                Segment(speaker="温棠", speaker_type=SpeakerType.BOT,
                        text="（久久没有说话，最终俯身）……臣妾谢陛下。",
                        emotion_tag="难以置信"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴琰抬起头，眼睛亮了。你看见他偷偷攥住了温棠的衣角。"),
            ],
            routes=[
                RouteCondition(condition="hasFlag 'p_protected_wentang'", next="p_ending_true"),
                RouteCondition(condition="hasFlag 'p_went_to_visit'", next="p_ending_true"),
                RouteCondition(condition="hasFlag 'p_found_peace'", next="p_ending_true"),
                RouteCondition(condition="default", next="p_ending_normal"),
            ],
        ),

        # ─── 结局 ───
        "p_ending_true": StoryNode(
            node_id="p_ending_true",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="温暖",
            is_ending=True,
            ending_type="圆满",
            ending_title="结局·天子亦有软肋",
            ending_description="温棠封妃，裴琰得到了父皇久违的目光。采桑宫成了你偶尔躲开朝堂的地方——不是因为权谋，只是那里有一碗甜汤，和两个不要求你是天子的人。",
            ending_closing="你后来想，做皇帝，要的是天下太平。但有时候，一室安静也很好。",
        ),

        "p_ending_normal": StoryNode(
            node_id="p_ending_normal",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="平静",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·御旨已下",
            ending_description="温棠晋了位份，裴琰有了庇护。你完成了一件该做的事，处置得当，后宫稳定。只是离开采桑宫时，你没有回头——也许有什么，就这样错过了。",
            ending_closing="天子做了无数决定，只有少数几个，是为了自己。",
        ),

        "p_ending_bad": StoryNode(
            node_id="p_ending_bad",
            act=3,
            scene_name="御书房",
            progress=100,
            ambient="冷肃",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·朕心难测",
            ending_description="皇后的压力最终奏效，温棠在后宫愈发举步维艰。裴琰长大后，眼神里再看不到那年的温软。你翻过太多牌子，唯独忘了，有些事搁置太久，就真的回不去了。",
            ending_closing="皇权赐予的，皇权能拿回。但有些东西，失去了就是失去了。",
        ),
    },
)


# ── 向后兼容：保留原始名称 ──
HUATANGCHUN = HUATANGCHUN_WENTANG


# ══════════════════════════════════════════════════════
#  《画堂春》双人 MOOK 剧本
#  温棠（玩家A）× 裴容（玩家B）共同演绎
#  mook_active_role 标记当前该谁做选择
# ══════════════════════════════════════════════════════
HUATANGCHUN_MOOK = StoryScript(
    meta=StoryMeta(
        story_id="huatangchun_mook",
        title="画堂春·共此时",
        author="AI生成",
        genre="古风宫廷双人互动",
        world_setting="前朝遗事将覆，新帝初立，采桑宫的灯还亮着。温棠与裴容，一个是宫妃，一个是皇子，同住一处，却各有心事。",
        max_players=2,
        min_players=2,
        roles=[
            RoleProfile(
                role_id="wentang",
                name="温棠",
                identity="采桑宫宫妃，出身寒微，以才入宫",
                personality="聪慧内敛，表面从容，心中藏着许多未说出口的话",
                speaking_style="轻声细语，偶有俏皮，话里总留三分余地",
                core_purpose="在宫中寻得一片安稳，护住自己在意的人",
                trigger_points=["被轻视出身时", "裴容受到伤害时"],
                weakness="太过顾全大局，有时压抑自己的真实情绪",
                playable=True,
                required=True,
            ),
            RoleProfile(
                role_id="peirong",
                name="裴容",
                identity="皇三子，封闲王，住采桑宫偏殿",
                personality="外冷内热，刀子嘴豆腐心，习惯用刻薄掩盖在乎",
                speaking_style="言辞简练，惯用反问，偶尔会冒出一句很软的话让人意外",
                core_purpose="弄清楚自己和温棠之间到底是什么",
                trigger_points=["被人说「不如其他兄弟」时", "温棠陷入危险时"],
                weakness="认定的事很难回头，但认定之前要走很长的弯路",
                playable=True,
                required=True,
            ),
        ],
        start_node_id="mook_start",
    ),
    nodes={
        # ────────────── 第一幕：采桑宫的雨夜 ──────────────
        "mook_start": StoryNode(
            node_id="mook_start",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="秋雨不期而至，回廊的灯笼被风吹得摇曳。温棠抱着一摞书册躲进廊下，正好撞上也在避雨的裴容。",
            ambient="秋雨·廊灯摇曳",
            progress=5,
            mook_active_role="",  # 旁白节点，无需选择
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="秋雨骤至，采桑宫回廊的灯笼在风里颤着，光影斑驳地落在青石地面上。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="静谧",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠抱着一摞书册跌跌撞撞躲进廊下，发现廊柱旁已经站着一个人——是裴容，三皇子，那个住在偏殿、平日里几乎不出门的人。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="意外",
                ),
                Segment(
                    speaker="裴容",
                    speaker_type=SpeakerType.BOT,
                    text="……你也在这里。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="淡漠",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_wt_choice_1")],
        ),

        # 温棠的第一次选择
        "mook_wt_choice_1": StoryNode(
            node_id="mook_wt_choice_1",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="裴容冷淡地说了一句「你也在这里」，温棠该如何回应？",
            ambient="秋雨·廊灯摇曳",
            progress=15,
            mook_active_role="wentang",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="廊外雨声沙沙，两人之间隔着半丈距离，气氛有些微妙。裴容侧过脸，看了温棠一眼，没有再说话。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="微妙",
                ),
            ],
            choices=[
                Choice(
                    text="主动开口，打破沉默（「下这么大的雨，殿下也没带伞？」）",
                    next="mook_pr_choice_1a",
                    effect="温棠率先打破僵局",
                    influence_hint="裴容对温棠的警惕稍减",
                    changes={"wentang_peirong": 5},
                ),
                Choice(
                    text="也沉默，只是轻轻点头致意",
                    next="mook_pr_choice_1b",
                    effect="温棠选择保持距离",
                    influence_hint="两人都保留着自己的边界",
                    changes={"wentang_peirong": 0},
                ),
                Choice(
                    text="半开玩笑打圆场（「这廊子也就这么宽，殿下别嫌挤。」）",
                    next="mook_pr_choice_1c",
                    effect="温棠用轻巧的语气化解尴尬",
                    influence_hint="裴容意外地没有回怼",
                    changes={"wentang_peirong": 8},
                ),
            ],
        ),

        # 裴容的第一次选择（路径A：温棠主动打破沉默）
        "mook_pr_choice_1a": StoryNode(
            node_id="mook_pr_choice_1a",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="温棠先开了口。裴容该怎么接？",
            ambient="秋雨·廊灯摇曳",
            progress=25,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="下这么大的雨，殿下也没带伞？",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="轻巧",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容顿了一下，视线落在温棠抱着的那摞已被雨水打湿了边角的书册上。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="凝视",
                ),
            ],
            choices=[
                Choice(
                    text="淡淡接话（「你的书湿了。」）",
                    next="mook_act1_branch_warm",
                    effect="裴容用一句话把注意力转到温棠的书上",
                    influence_hint="温棠发现他其实在意",
                    changes={"wentang_peirong": 10},
                ),
                Choice(
                    text="反问（「带了又如何，你来这里做什么？」）",
                    next="mook_act1_branch_neutral",
                    effect="裴容把话头又推回给温棠",
                    influence_hint="两人开始真正地说话了",
                    changes={"wentang_peirong": 3},
                ),
            ],
        ),

        # 裴容的第一次选择（路径B：温棠沉默点头）
        "mook_pr_choice_1b": StoryNode(
            node_id="mook_pr_choice_1b",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="两人各自沉默，雨声填满了间隙。裴容先开了口——还是就这么耗下去？",
            ambient="秋雨·廊灯摇曳",
            progress=25,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="两人各自撑着沉默，雨声越来越大。温棠低头看了眼怀里被打湿的书角，没有开口。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="凝滞",
                ),
            ],
            choices=[
                Choice(
                    text="先开口（「你那书，放我这边。」说着侧了侧身，把自己这边稍干的地方让出来）",
                    next="mook_act1_branch_warm",
                    effect="裴容主动让出了干燥的地方",
                    influence_hint="温棠愣了一下",
                    changes={"wentang_peirong": 12},
                ),
                Choice(
                    text="继续沉默，把目光转向廊外的雨",
                    next="mook_act1_branch_neutral",
                    effect="两人谁也没有先动",
                    influence_hint="沉默本身也是一种相处方式",
                    changes={"wentang_peirong": 0},
                ),
            ],
        ),

        # 裴容的第一次选择（路径C：温棠开玩笑）
        "mook_pr_choice_1c": StoryNode(
            node_id="mook_pr_choice_1c",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="温棠开了个小玩笑。裴容怎么接？",
            ambient="秋雨·廊灯摇曳",
            progress=25,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="这廊子也就这么宽，殿下别嫌挤。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="俏皮",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容看了她一眼，眉峰微动，像是没料到这句话。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="意外",
                ),
            ],
            choices=[
                Choice(
                    text="接了这个梗（「谁嫌挤了。」说完，往旁边挪了一步）",
                    next="mook_act1_branch_warm",
                    effect="裴容嘴上反驳，身体却让了步",
                    influence_hint="温棠忍住了笑",
                    changes={"wentang_peirong": 15},
                ),
                Choice(
                    text="不接话，只是若无其事地看向别处",
                    next="mook_act1_branch_neutral",
                    effect="裴容没有回应这个玩笑",
                    influence_hint="但温棠发现他嘴角动了一下",
                    changes={"wentang_peirong": 5},
                ),
            ],
        ),

        # ────────────── 第一幕收束：两条支线合流 ──────────────
        "mook_act1_branch_warm": StoryNode(
            node_id="mook_act1_branch_warm",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="雨渐渐小了，两人之间的距离也悄悄近了一些。",
            ambient="雨歇·夜深",
            progress=35,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="雨小了。廊灯的光晕将两人的影子压在一起，像一幅随意的画。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="温柔",
                ),
                Segment(
                    speaker="裴容",
                    speaker_type=SpeakerType.BOT,
                    text="……雨停了，你先回去吧。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="低沉",
                ),
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="好。殿下也早些回。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="轻软",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="走出几步，温棠回头，看见裴容还站在原处，看着廊外发呆。她没有叫他，只是转过身继续走。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="若有所思",
                    card_type="人物档案",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_act2_start")],
        ),

        "mook_act1_branch_neutral": StoryNode(
            node_id="mook_act1_branch_neutral",
            act=1,
            act_title="第一幕·雨夜偶遇",
            scene_name="采桑宫回廊",
            scene_description="雨停了，两人各自散去，像是什么都没发生过。",
            ambient="雨歇·夜深",
            progress=35,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="雨停了，各自散去。那段廊下的沉默像一块未经打磨的石头，谁也不知道它最终会变成什么。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="平淡",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_act2_start")],
        ),

        # ────────────── 第二幕：一封不该送到的信 ──────────────
        "mook_act2_start": StoryNode(
            node_id="mook_act2_start",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="采桑宫书房",
            scene_description="隔了三日，温棠在书案上发现了一封信——信皮上的字迹是裴容的，但显然是送错了地方。",
            ambient="午后·静",
            progress=40,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="三日后，午后，书房，一封信压在砚台下。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="平静",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠拿起来，认出那是裴容的字迹，信皮上写着「交采桑宫东厢管事」——东厢是偏殿，这封信送错了。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="困惑",
                    card_type="当前线索",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_wt_choice_2")],
        ),

        # 温棠的第二次选择
        "mook_wt_choice_2": StoryNode(
            node_id="mook_wt_choice_2",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="采桑宫书房",
            scene_description="这封本该送往裴容偏殿的信现在在温棠手里，她该怎么处理？",
            ambient="午后·静",
            progress=48,
            mook_active_role="wentang",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="信还未拆封。温棠拿在手里，掂量着。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="思索",
                ),
            ],
            choices=[
                Choice(
                    text="亲自送去偏殿，顺便敲门（「殿下，有您的信送错地方了。」）",
                    next="mook_pr_choice_2a",
                    effect="温棠亲自上门，两人又多了一次交集",
                    influence_hint="裴容开门的瞬间愣了一下",
                    changes={"wentang_peirong": 8, "addFlag": "wt_delivered_letter"},
                ),
                Choice(
                    text="交给小厮转送，不去打扰",
                    next="mook_pr_choice_2b",
                    effect="温棠保持了边界",
                    influence_hint="裴容收到信时，多看了那个小厮一眼",
                    changes={"wentang_peirong": 0},
                ),
                Choice(
                    text="放在原处等裴容自己来取（或许他知道送错了会来找）",
                    next="mook_pr_choice_2c",
                    effect="温棠什么都没做，只是等",
                    influence_hint="裴容确实来了",
                    changes={"wentang_peirong": 5, "addFlag": "wt_waited_letter"},
                ),
            ],
        ),

        # 裴容视角：收到信后的反应（路径A：温棠亲自来送）
        "mook_pr_choice_2a": StoryNode(
            node_id="mook_pr_choice_2a",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="偏殿门口",
            scene_description="温棠亲自把信送来了，裴容开了门。他怎么接这件事？",
            ambient="午后·静",
            progress=55,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="殿下，有封信送错地方了，是您的。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="从容",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容接过信，低头看了眼信皮，沉默了一会儿。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="停顿",
                ),
            ],
            choices=[
                Choice(
                    text="直接道谢，然后说（「你进来坐。」）",
                    next="mook_act2_branch_close",
                    effect="裴容罕见地主动邀请",
                    influence_hint="温棠怔了一下",
                    changes={"wentang_peirong": 15, "addFlag": "pr_invited_in"},
                ),
                Choice(
                    text="只说了一个「嗯」，接过信就关门",
                    next="mook_act2_branch_distant",
                    effect="裴容的反应和往常一样冷",
                    influence_hint="温棠转身时，听见了里面传出翻信纸的声音",
                    changes={"wentang_peirong": 2},
                ),
            ],
        ),

        # 裴容视角：温棠托小厮送信
        "mook_pr_choice_2b": StoryNode(
            node_id="mook_pr_choice_2b",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="偏殿",
            scene_description="信通过小厮转到了裴容手中。他该怎么看待这件事？",
            ambient="午后·偏殿",
            progress=55,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="小厮把信递来，说是温娘娘让转的。裴容接过，没说什么，把小厮打发走了。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="平淡",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="信是关于宫中用度的例行文书，没什么要紧的。但裴容盯着信皮上自己的名字看了一会儿。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="若有所思",
                ),
            ],
            choices=[
                Choice(
                    text="写一张便条让人转回去，只写了「收到，谢」三个字",
                    next="mook_act2_branch_distant",
                    effect="裴容回了礼，但保持着距离",
                    influence_hint="温棠收到便条时，盯着那三个字看了好一会儿",
                    changes={"wentang_peirong": 5},
                ),
                Choice(
                    text="什么都不做，当作寻常",
                    next="mook_act2_branch_distant",
                    effect="裴容没有任何回应",
                    influence_hint="温棠没有等到回音",
                    changes={"wentang_peirong": 0},
                ),
            ],
        ),

        # 裴容视角：温棠把信留在原处等他来取
        "mook_pr_choice_2c": StoryNode(
            node_id="mook_pr_choice_2c",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="采桑宫书房",
            scene_description="裴容来取信了。两人在书房相遇，他该说什么？",
            ambient="午后·书房",
            progress=55,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="片刻后，门被轻叩了两下。裴容推门进来，直接走向砚台，取起那封信。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="直接",
                ),
                Segment(
                    speaker="裴容",
                    speaker_type=SpeakerType.BOT,
                    text="麻烦了。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="简短",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠抬头，发现他没有立刻走，而是站在原地，似乎有什么话要说。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="等待",
                ),
            ],
            choices=[
                Choice(
                    text="开口说（「昨晚那场雨，你的书没事吧？」）",
                    next="mook_act2_branch_close",
                    effect="裴容提起了雨夜的事",
                    influence_hint="温棠没想到他记着这件事",
                    changes={"wentang_peirong": 12, "addFlag": "pr_remembered_rain"},
                ),
                Choice(
                    text="什么都没说，转身出门",
                    next="mook_act2_branch_distant",
                    effect="裴容还是没能开口",
                    influence_hint="温棠的目光跟了他一路",
                    changes={"wentang_peirong": 3},
                ),
            ],
        ),

        # ────────────── 第二幕收束 ──────────────
        "mook_act2_branch_close": StoryNode(
            node_id="mook_act2_branch_close",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="采桑宫",
            scene_description="这件小事，让两人之间多了一道细微的裂缝——或者说，是一条细微的通道。",
            ambient="午后·明亮",
            progress=65,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="事情就这样过去了，但不知为何，采桑宫的下午好像比以前长了一些。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="温柔",
                    card_type="旧事回忆",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_act3_start")],
        ),

        "mook_act2_branch_distant": StoryNode(
            node_id="mook_act2_branch_distant",
            act=2,
            act_title="第二幕·误入的信",
            scene_name="采桑宫",
            scene_description="一切恢复平静，仿佛什么都没有发生。",
            ambient="午后·平静",
            progress=65,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="采桑宫依旧寂静。那封信的事，很快就没有人再提了。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="平淡",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_act3_start")],
        ),

        # ────────────── 第三幕：宫宴之前 ──────────────
        "mook_act3_start": StoryNode(
            node_id="mook_act3_start",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            scene_description="宫宴将至，温棠在庭院里对着铜镜整理发髻。裴容经过，停下了脚步。",
            ambient="黄昏·宫宴前",
            progress=70,
            mook_active_role="",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="宫宴的请帖三日前就到了。温棠对着铜镜整理着发髻，簪子插了又拔，拔了又插。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="紧张",
                ),
                Segment(
                    speaker="裴容",
                    speaker_type=SpeakerType.BOT,
                    text="你那簪子戴歪了。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="随口",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠在镜中看见裴容站在院门口，不知道他在那里站了多久。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="意外",
                ),
            ],
            routes=[RouteCondition(condition="default", next="mook_wt_choice_3")],
        ),

        # 温棠的第三次选择
        "mook_wt_choice_3": StoryNode(
            node_id="mook_wt_choice_3",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            scene_description="裴容说簪子戴歪了——温棠怎么回应这个意料之外的开口？",
            ambient="黄昏·宫宴前",
            progress=76,
            mook_active_role="wentang",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="簪子戴歪了。温棠对着镜子看了一眼，确实。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="发现",
                ),
            ],
            choices=[
                Choice(
                    text="调侃他（「殿下是路过，还是特地来看我戴歪的？」）",
                    next="mook_pr_choice_3a",
                    effect="温棠以玩笑应对，把球踢了回去",
                    influence_hint="裴容没有走",
                    changes={"wentang_peirong": 8, "addFlag": "wt_teased_pr"},
                ),
                Choice(
                    text="认真问（「怎么个歪法，殿下帮我看看？」）",
                    next="mook_pr_choice_3b",
                    effect="温棠大方地请他帮忙",
                    influence_hint="裴容愣了片刻",
                    changes={"wentang_peirong": 12},
                ),
                Choice(
                    text="低头重新整理，没有接话",
                    next="mook_pr_choice_3c",
                    effect="温棠只是默默调整，没有搭话",
                    influence_hint="裴容在门口多站了一会儿",
                    changes={"wentang_peirong": 3},
                ),
            ],
        ),

        # 裴容的第三次选择（路径A：被调侃）
        "mook_pr_choice_3a": StoryNode(
            node_id="mook_pr_choice_3a",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            scene_description="温棠调侃了他，裴容没走。他现在怎么接？",
            ambient="黄昏·宫宴前",
            progress=82,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="殿下是路过，还是特地来看我戴歪的？",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="俏皮",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容没说话，走了进来，站在她身后。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="靠近",
                ),
            ],
            choices=[
                Choice(
                    text="伸手，替她把簪子正了（什么都没说）",
                    next="mook_ending_warm",
                    effect="裴容用行动代替了语言",
                    influence_hint="温棠在镜中看着他的手，屏住了呼吸",
                    changes={"wentang_peirong": 20, "addFlag": "pr_fixed_hairpin"},
                ),
                Choice(
                    text="说（「路过。你自己照着镜子弄。」）但没有走",
                    next="mook_ending_neutral",
                    effect="裴容嘴上说着路过，脚却没动",
                    influence_hint="温棠笑了笑，没有戳穿他",
                    changes={"wentang_peirong": 10},
                ),
            ],
        ),

        # 裴容的第三次选择（路径B：被请求帮忙）
        "mook_pr_choice_3b": StoryNode(
            node_id="mook_pr_choice_3b",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            scene_description="温棠请他帮忙看发髻。裴容该怎么做？",
            ambient="黄昏·宫宴前",
            progress=82,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="温棠",
                    speaker_type=SpeakerType.PLAYER,
                    text="怎么个歪法，殿下帮我看看？",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="坦然",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容愣了片刻。这个问题让他有些没有预料到。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="停顿",
                ),
            ],
            choices=[
                Choice(
                    text="走过来，俯身看了一眼，替她把簪子重新别好",
                    next="mook_ending_warm",
                    effect="裴容认真地帮了她",
                    influence_hint="两人在镜中对了一眼",
                    changes={"wentang_peirong": 18, "addFlag": "pr_fixed_hairpin"},
                ),
                Choice(
                    text="说（「你自己对着镜子，左边压低一点。」）没有走过来",
                    next="mook_ending_neutral",
                    effect="裴容用语言指导，但保持了距离",
                    influence_hint="温棠按他说的调了调，正了",
                    changes={"wentang_peirong": 8},
                ),
            ],
        ),

        # 裴容的第三次选择（路径C：温棠没接话）
        "mook_pr_choice_3c": StoryNode(
            node_id="mook_pr_choice_3c",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            scene_description="温棠没有接话，只是低头重新整理。裴容还站在那里。他该怎么办？",
            ambient="黄昏·宫宴前",
            progress=82,
            mook_active_role="peirong",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠低下头，对着铜镜重新整理发髻，没有应声。裴容站在门口，一时也没有走。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="僵住",
                ),
            ],
            choices=[
                Choice(
                    text="走进去说（「往左一点。」然后在她身后停下来）",
                    next="mook_ending_neutral",
                    effect="裴容终于开口，替她指路",
                    influence_hint="温棠抬起头，在镜中看见了他",
                    changes={"wentang_peirong": 10},
                ),
                Choice(
                    text="转身离开，说（「宫宴快了，别迟到。」）",
                    next="mook_ending_cold",
                    effect="裴容找了个台阶下，走了",
                    influence_hint="温棠把簪子插好，盯着镜子里的自己发了会儿呆",
                    changes={"wentang_peirong": -2},
                ),
            ],
        ),

        # ────────────── 结局节点 ──────────────
        "mook_ending_warm": StoryNode(
            node_id="mook_ending_warm",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            progress=100,
            ambient="黄昏·金光",
            is_ending=True,
            ending_type="圆满",
            ending_title="结局·不只是路过",
            ending_description="那枚簪子，后来被温棠一直戴着。裴容从没有问过为什么，温棠也没有解释。采桑宫的宫宴结束得很晚，他们并排走回去，月光压着影子，谁也没有先说话——但那个沉默，和雨夜回廊里的那次，已经全然不同了。",
            ending_closing="有些话不必说出来，因为已经都知道了。",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="他的手指轻轻碰到她的发，把那枚歪斜的簪子重新别好。镜子里，两个人的眼神对上了一瞬，又各自移开。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="心动",
                    card_type="旧事回忆",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="宫宴散后，裴容等在回廊处，只说了一句：「走吧。」",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="温柔",
                ),
            ],
        ),

        "mook_ending_neutral": StoryNode(
            node_id="mook_ending_neutral",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            progress=100,
            ambient="黄昏·微风",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·往左一点",
            ending_description="簪子戴正了，宫宴也去了。温棠在人群里找过一次裴容的方向，但人太多，没有找到。裴容那边，宴席上有人来劝酒，他喝了，没有和任何人多说话。回程的路上，两人各走各的，像往常一样。只是步子，都慢了一些。",
            ending_closing="有些靠近，要一点一点来，不能急。",
            segments=[
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="簪子正了。温棠对着镜子看了一眼，轻声道了句谢。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="平静",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="裴容没有回答，只是走了。采桑宫的黄昏比往日更安静一点。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="若有所思",
                ),
            ],
        ),

        "mook_ending_cold": StoryNode(
            node_id="mook_ending_cold",
            act=3,
            act_title="第三幕·宫宴前夕",
            scene_name="采桑宫庭院",
            progress=100,
            ambient="黄昏·将暗",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·宫宴快了",
            ending_description="宫宴还是去了，各坐各的席，各行各的礼。温棠在座上偶尔抬头，裴容始终没有看向她那边。散席之后，温棠先走了，裴容在原地又坐了一会儿，盯着那盏快要熄的灯发呆。他没有想清楚自己在等什么。",
            ending_closing="错过不是一瞬间的事，是一次次选择慢慢积累的。",
            segments=[
                Segment(
                    speaker="裴容",
                    speaker_type=SpeakerType.BOT,
                    text="宫宴快了，别迟到。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="冷淡",
                ),
                Segment(
                    speaker="旁白",
                    speaker_type=SpeakerType.NARRATOR,
                    text="温棠把簪子插好，盯着镜子里的自己发了会儿呆，才起身去换衣裳。",
                    input_mode=InputMode.NARRATION,
                    emotion_tag="落寞",
                ),
            ],
        ),
    },
)
