"""《画堂春》完整剧本 JSON"""
from app.models import (
    StoryScript, StoryMeta, StoryNode, RoleProfile,
    Segment, Choice, RouteCondition,
    InputMode, SpeakerType
)

HUATANGCHUN = StoryScript(
    meta=StoryMeta(
        story_id="huatangchun",
        title="画堂春",
        author="鸠森",
        source_url="https://www.zhihu.com/market/paid_column/1725479677609644032/section/1935677831142171296",
        genre="古言",
        world_setting="架空封建王朝后宫，皇权至上，等级森严。后宫争宠夺权与皇子抚育权争夺是核心冲突。",
        max_players=5,
        min_players=1,
        roles=[
            RoleProfile(
                role_id="wentang",
                name="温棠",
                identity="温贵人，入宫十年，四皇子生母",
                personality="温和隐忍，善良心软，不争不抢，胆小求稳",
                speaking_style="语气温和，偶尔结巴，对皇帝恭敬，对裴琰温柔",
                core_purpose="活下去，守护孩子，弥补对两个孩子的亏欠",
                trigger_points=["制作枣花糕", "缝补衣物", "试图接近裴瑜", "保护裴琰"],
                weakness="心软，胆小，对裴瑜的执念",
                playable=True,
                required=True,
                avatar_prompt="温婉女子，素衣淡妆，眉眼柔和，手中握着枣花糕",
            ),
            RoleProfile(
                role_id="peirong",
                name="裴容",
                identity="大胤皇帝，后宫与朝堂的绝对主宰",
                personality="喜怒不形于色，理性凉薄，皇权至上，看重温顺贤德",
                speaking_style="语气平淡沉稳，带帝王威严，说话简洁偶尔反问",
                core_purpose="平衡后宫势力，妥善安置皇子，维持统治稳定",
                trigger_points=["翻牌子", "视察各宫", "询问皇子近况"],
                weakness="对安宁纯粹的氛围没抵抗力，念旧情",
                playable=True,
                required=False,
                avatar_prompt="帝王装扮，面容冷峻，龙袍手持书卷，喜怒不形于色",
            ),
            RoleProfile(
                role_id="peiyan",
                name="裴琰",
                identity="三皇子，废贵妃之子，9岁",
                personality="早熟隐忍，敏感懂事，察言观色极强，知恩图报",
                speaking_style="语气乖巧小心翼翼，对温棠温柔依赖，紧张时磕巴",
                core_purpose="报答温棠，帮温棠争宠，保护温棠",
                trigger_points=["接受枣花糕", "帮温棠出主意", "被裴瑜欺负"],
                weakness="内心敏感，害怕被抛弃，面对强势者本能退缩",
                playable=True,
                required=False,
                avatar_prompt="瘦弱少年，面色苍白，衣着朴素，眼神早熟却藏着温顺",
            ),
            RoleProfile(
                role_id="peiyu",
                name="裴瑜",
                identity="四皇子，温棠亲生儿子，皇后养子，8岁",
                personality="骄纵傲慢，趋炎附势，自私自利，看不起低位者",
                speaking_style="语气骄纵偏快带傲气，对温棠轻蔑，对皇后撒娇",
                core_purpose="获得皇后宠爱，彰显优越感",
                trigger_points=["欺负裴琰", "嘲讽温棠", "向皇后撒娇"],
                weakness="过于依赖皇后，内心深处渴望母爱",
                playable=True,
                required=False,
                avatar_prompt="锦衣少年，面容娇俏，眼神骄纵，身着华贵服饰",
            ),
            RoleProfile(
                role_id="chenmomo",
                name="陈嬷嬷",
                identity="温棠同乡，温棠贴身嬷嬷",
                personality="慈心善良，通透世故，深谙后宫生存之道",
                speaking_style="语气温和平缓，对温棠真诚直白，对皇帝皇后不卑不亢",
                core_purpose="保护温棠不受伤害，看着温棠获得好结局",
                trigger_points=["给温棠提建议", "提醒温棠避祸", "安慰失意的温棠"],
                weakness="过于在意温棠，容易因温棠安危乱了分寸",
                playable=True,
                required=False,
                avatar_prompt="年长嬷嬷，衣着朴素，面容慈祥，眼神通透",
            ),
        ],
        start_node_id="act1_start",
    ),
    nodes={
        # ─── 第一幕：雪夜承宠 ───
        "act1_start": StoryNode(
            node_id="act1_start",
            act=1,
            act_title="第一幕 · 雪夜承宠",
            scene_name="采桑宫偏殿",
            scene_description="夜深了，窗外雪落无声，采桑宫的灯火难得点着。",
            ambient="静谧",
            progress=5,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="入宫十年，温棠早已习惯了被遗忘的滋味。今夜，窗外雪落无声，采桑宫偏殿里，她独自坐着，手边摆着一碟枣花糕——这是她唯一拿得出手的东西。",
                        input_mode=InputMode.NARRATION),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="贵人，仇公公来了，说……说陛下今夜要翻您的牌子。",
                        input_mode=InputMode.FIXED, emotion_tag="惊讶"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="听到这消息，你心里……",
                        input_mode=InputMode.GUIDED,
                        guided_options=["惊喜，连忙整理仪容", "惊慌，不知所措", "平静，这只是意外"]),
            ],
            choices=[
                Choice(text="惊喜，连忙整理仪容", next="act1_arrive_emperor",
                       changes={"val": 5, "wentang_peirong": 5},
                       influence_hint="皇帝注意到你的慌乱与真诚"),
                Choice(text="惊慌，不知所措", next="act1_arrive_emperor",
                       changes={"val": 0},
                       influence_hint="皇帝感受到了你的紧张"),
                Choice(text="平静，这只是意外", next="act1_arrive_emperor",
                       changes={"val": -5, "wentang_peirong": 2},
                       influence_hint="皇帝对你的淡然有些意外"),
            ],
        ),

        "act1_arrive_emperor": StoryNode(
            node_id="act1_arrive_emperor",
            act=1,
            scene_name="采桑宫偏殿",
            scene_description="皇帝驾临，采桑宫偏殿灯火通明。",
            progress=15,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴容步入采桑宫，目光扫过简陋的陈设，在那碟枣花糕上停了一瞬。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕记得，你入宫时带了一手做枣花糕的本事。",
                        input_mode=InputMode.FIXED, emotion_tag="平淡"),
            ],
            choices=[
                Choice(text="「臣妾做的不好，让陛下见笑了。」", next="act1_peiyan_question",
                       changes={"val": 5, "wentang_peirong": 8},
                       influence_hint="皇帝对你的谦逊印象不错"),
                Choice(text="「陛下还记得？臣妾……臣妾很高兴。」", next="act1_peiyan_question",
                       changes={"val": 8, "wentang_peirong": 12},
                       influence_hint="真情流露，皇帝眼神柔和了一瞬"),
                Choice(text="「臣妾备了红豆甜汤，陛下可要尝尝？」", next="act1_peiyan_question",
                       changes={"val": 3, "wentang_peirong": 6},
                       influence_hint="皇帝接过汤，沉默地喝了一口"),
            ],
        ),

        "act1_peiyan_question": StoryNode(
            node_id="act1_peiyan_question",
            act=1,
            scene_name="采桑宫偏殿",
            progress=30,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕问你，三皇子琰儿如今无人抚育，你……可愿接手？",
                        input_mode=InputMode.FIXED, emotion_tag="观察"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="这是一道难题。抚育失势皇子，是祸是福，无人说得清。"),
            ],
            choices=[
                Choice(text="「臣妾愿悉心照料琰儿。」", next="act1_peiyan_accept",
                       changes={"wentang_peirong": 10, "wentang_peiyan": 15, "addFlag": "accepted_peiyan"},
                       influence_hint="裴容亲密度+10，裴琰亲密度+15，解锁剧情「采桑宫温居」"),
                Choice(text="「陛下，琰儿乃皇子，臣妾恐难当此任……」", next="act1_peiyan_hesitate",
                       changes={"wentang_peirong": 5, "wentang_peiyan": 5},
                       influence_hint="皇帝目光变得沉沉的"),
                Choice(text="「臣妾只想盼着瑜儿回心转意……」", next="act1_peiyan_refuse",
                       changes={"wentang_peirong": -5, "wentang_peiyu": 5, "addFlag": "refused_peiyan"},
                       influence_hint="皇帝沉默了很久"),
            ],
        ),

        "act1_peiyan_accept": StoryNode(
            node_id="act1_peiyan_accept",
            act=1,
            scene_name="采桑宫偏殿",
            progress=45,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="好。明日圣旨下达，琰儿便送入采桑宫。",
                        emotion_tag="满意"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="他走了，留下一室安静。你握着那碟枣花糕，不知这是幸还是不幸。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="🎉 解锁「采桑宫温居」支线！第一幕完成。",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_start")],
        ),

        "act1_peiyan_hesitate": StoryNode(
            node_id="act1_peiyan_hesitate",
            act=1,
            scene_name="采桑宫偏殿",
            progress=40,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="你害怕什么？",
                        emotion_tag="审视"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act1_peiyan_accept")],
        ),

        "act1_peiyan_refuse": StoryNode(
            node_id="act1_peiyan_refuse",
            act=1,
            scene_name="采桑宫偏殿",
            progress=35,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="……罢了。",
                        emotion_tag="冷淡"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="皇帝对你的印象有所下降。裴琰仍无人抚育……",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_start_no_peiyan")],
        ),

        # ─── 第二幕：抚育之诺 ───
        "act2_start": StoryNode(
            node_id="act2_start",
            act=2,
            act_title="第二幕 · 抚育之诺",
            scene_name="采桑宫正殿",
            scene_description="次日清晨，圣旨下达。裴琰站在采桑宫门口，瘦弱的身影让温棠心疼。",
            ambient="清晨",
            progress=50,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="圣旨下了。裴琰被送来采桑宫——一个瘦弱的孩子，眼神里藏着远超年龄的戒备。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……您就是温贵人？",
                        input_mode=InputMode.FIXED, emotion_tag="戒备"),
            ],
            choices=[
                Choice(text="「是我。以后这里就是你的家。」", next="act2_warmth",
                       changes={"wentang_peiyan": 20, "val": 5, "addFlag": "warm_welcome"},
                       influence_hint="裴琰愣了一下，眼眶微红"),
                Choice(text="「你饿了吗？我做了枣花糕。」", next="act2_cake",
                       changes={"wentang_peiyan": 15, "val": 3},
                       influence_hint="裴琰看着那碟糕点，攥紧了衣角"),
                Choice(text="先打量他，沉默片刻再开口", next="act2_silent",
                       changes={"wentang_peiyan": 5},
                       influence_hint="孩子的戒备没有消散"),
            ],
        ),

        "act2_warmth": StoryNode(
            node_id="act2_warmth",
            act=2,
            scene_name="采桑宫正殿",
            progress=60,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……您不怕抚育我会惹祸？",
                        emotion_tag="困惑又期待"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act2_peiyu_bully")],
        ),

        "act2_cake": StoryNode(
            node_id="act2_cake",
            act=2,
            scene_name="采桑宫正殿",
            progress=58,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（沉默地接过，小口咬了一口）……甜的。",
                        emotion_tag="戒备渐消"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="裴琰信任值 +8",
                        card_type="当前线索"),
            ],
            routes=[RouteCondition(condition="default", next="act2_peiyu_bully")],
        ),

        "act2_silent": StoryNode(
            node_id="act2_silent",
            act=2,
            scene_name="采桑宫正殿",
            progress=55,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（低头，不再说话）",
                        emotion_tag="失落"),
            ],
            routes=[RouteCondition(condition="default", next="act2_bond")],
        ),


        # ─── 第二幕：冲突节点 ───
        "act2_peiyu_bully": StoryNode(
            node_id="act2_peiyu_bully",
            act=2,
            scene_name="采桑宫院子",
            scene_description="裴瑜带着几个小太监闯入采桑宫，看到裴琰时，眼里满是轻蔑。",
            progress=62,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="第三天，麻烦来了。裴瑜不知从哪听说了裴琰被送到采桑宫的消息。"),
                Segment(speaker="裴瑜", speaker_type=SpeakerType.BOT,
                        text="哟，废妃的崽子，在这吃得挺好嘛。这枣花糕也配你吃？",
                        input_mode=InputMode.FIXED, emotion_tag="嘲讽"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（裴琰攥紧拳头，低着头一言不发。）",
                        emotion_tag="隐忍"),
            ],
            choices=[
                Choice(text="挡在裴琰面前：「四殿下，采桑宫不欢迎不请自来的客人。」",
                       next="act2_protect_peiyan",
                       changes={"val": 10, "wentang_peiyan": 20, "wentang_peiyu": -10, "addFlag": "protected_peiyan"},
                       influence_hint="裴琰眼眶泛红，裴瑜气得跺脚"),
                Choice(text="假装没看见，低头继续做针线",
                       next="act2_bond",
                       changes={"wentang_peiyan": -5},
                       influence_hint="裴琰的眼神暗了下去"),
                Choice(text="赔笑脸：「四殿下来了？快坐，臣妾给你做点心。」",
                       next="act2_bond",
                       changes={"wentang_peiyu": 5, "wentang_peiyan": -10},
                       influence_hint="裴琰安静地退到了角落"),
            ],
        ),

        "act2_protect_peiyan": StoryNode(
            node_id="act2_protect_peiyan",
            act=2,
            scene_name="采桑宫院子",
            progress=65,
            segments=[
                Segment(speaker="裴瑜", speaker_type=SpeakerType.BOT,
                        text="你——你算什么东西！我可是皇后娘娘养大的！",
                        emotion_tag="气急败坏"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴瑜甩袖而去，身后的小太监们慌忙跟上。你感到一只小手悄悄攥住了你的衣角。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="……母妃，你不怕他去告状吗？",
                        emotion_tag="担忧又感动"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act2_empress_warning")],
        ),

        "act2_empress_warning": StoryNode(
            node_id="act2_empress_warning",
            act=2,
            scene_name="采桑宫正殿",
            scene_description="傍晚，皇后身边的仇公公带来了一道口谕。",
            progress=68,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="果然，傍晚时分，仇公公就来了。"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="【剧情背景】仇公公是皇后的心腹，在宫中人人避之不及。他的出现意味着皇后已经知道了今天的事。",
                        card_type="当前线索"),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="（低声）贵人，来者不善。您千万别硬顶，先忍一忍。",
                        emotion_tag="紧张"),
            ],
            choices=[
                Choice(text="恭敬接旨，不做辩解",
                       next="act2_bond",
                       changes={"val": -5, "addFlag": "empress_warned"},
                       influence_hint="皇后暂时没有更多动作，但你知道她在看着"),
                Choice(text="委婉解释：「臣妾只是照顾陛下交代的孩子……」",
                       next="act2_bond",
                       changes={"val": 5, "wentang_peirong": 5, "addFlag": "used_emperor_shield"},
                       influence_hint="搬出皇帝，仇公公脸色变了变"),
            ],
        ),

        "act2_bond": StoryNode(
            node_id="act2_bond",
            act=2,
            scene_name="采桑宫正殿",
            progress=70,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="日子就这样过去了。裴琰开始帮你理账，帮你在皇帝面前说好话，用一个九岁孩子所能做的一切，偿还着你的善意。"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="母妃，我听说陛下喜欢喝红豆甜汤……您做得最好喝了，要不要让我帮您送过去？",
                        emotion_tag="认真"),
                Segment(speaker="系统", speaker_type=SpeakerType.SYSTEM,
                        text="🔗 裴琰主动帮温棠争宠，裴琰信任值大幅提升",
                        card_type="当前线索"),
            ],
            choices=[
                Choice(text="「你有这份心，母妃很高兴。」", next="act3_start",
                       changes={"wentang_peiyan": 15, "val": 5, "addFlag": "peiyan_help"},
                       influence_hint="裴琰眼睛亮了"),
                Choice(text="「不用，你还小，别掺和这些。」", next="act3_start",
                       changes={"wentang_peiyan": 5},
                       influence_hint="裴琰有些失落，但点了点头"),
            ],
        ),

        "act2_start_no_peiyan": StoryNode(
            node_id="act2_start_no_peiyan",
            act=2,
            act_title="第二幕 · 孤立无援",
            scene_name="采桑宫",
            progress=50,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="没有裴琰，采桑宫更冷清了。皇帝的翻牌也越来越少……"),
                Segment(speaker="陈嬷嬷", speaker_type=SpeakerType.BOT,
                        text="贵人，您真的不考虑重新请求陛下，把琰儿接来吗？",
                        emotion_tag="担忧"),
            ],
            choices=[
                Choice(text="「嬷嬷说得对，我去试试。」", next="act2_start",
                       changes={"addFlag": "accepted_peiyan", "wentang_peirong": -5}),
                Choice(text="「算了，我命如此。」", next="act3_bad_ending_route"),
            ],
        ),

        # ─── 第三幕：帝临采桑 ───
        "act3_start": StoryNode(
            node_id="act3_start",
            act=3,
            act_title="第三幕 · 帝临采桑",
            scene_name="采桑宫",
            scene_description="某日，皇帝驾临采桑宫。这一次，不是翻牌子，而是……",
            ambient="悬念",
            progress=80,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="裴容再次踏入采桑宫，目光在温棠与裴琰之间流转了一瞬。"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="朕听说……这孩子近来颇为懂事。",
                        emotion_tag="审视"),
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（悄悄拉了拉温棠的袖子，小声道）……母妃，红豆甜汤。",
                        emotion_tag="提醒"),
            ],
            choices=[
                Choice(text="立刻呈上红豆甜汤", next="act3_good_route",
                       changes={"wentang_peirong": 15, "val": 8, "addFlag": "sweet_soup_offered"},
                       influence_hint="皇帝接过，眼中有什么闪过"),
                Choice(text="先问皇帝今日来意", next="act3_ask_route",
                       changes={"wentang_peirong": 5},
                       influence_hint="皇帝对你的谨慎略感意外"),
                Choice(text="让裴琰亲手呈上", next="act3_peiyan_route",
                       changes={"wentang_peirong": 10, "wentang_peiyan": 10, "addFlag": "peiyan_served"},
                       influence_hint="皇帝看着裴琰，沉默良久"),
            ],
        ),

        "act3_good_route": StoryNode(
            node_id="act3_good_route",
            act=3,
            scene_name="采桑宫",
            progress=88,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="（喝了一口，沉默）……朕有意晋你为妃。",
                        emotion_tag="平静却有重量"),
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="这句话落在心里，温棠久久说不出话来。"),
            ],
            routes=[
                RouteCondition(condition="hasFlag 'peiyan_help'", next="ending_true"),
                RouteCondition(condition="default", next="ending_normal"),
            ],
        ),

        "act3_ask_route": StoryNode(
            node_id="act3_ask_route",
            act=3,
            scene_name="采桑宫",
            progress=85,
            segments=[
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="来看看这孩子，也看看你。",
                        emotion_tag="淡淡的"),
                Segment(speaker="温棠", speaker_type=SpeakerType.PLAYER,
                        text="",
                        input_mode=InputMode.FREE),
            ],
            routes=[RouteCondition(condition="default", next="act3_good_route")],
        ),

        "act3_peiyan_route": StoryNode(
            node_id="act3_peiyan_route",
            act=3,
            scene_name="采桑宫",
            progress=88,
            segments=[
                Segment(speaker="裴琰", speaker_type=SpeakerType.BOT,
                        text="（双手捧上，声音稳稳的）陛下，这是母妃亲手做的红豆甜汤，说陛下喜欢。",
                        emotion_tag="认真"),
                Segment(speaker="裴容", speaker_type=SpeakerType.BOT,
                        text="（接过，看着裴琰，久久不语）……",
                        emotion_tag="复杂"),
            ],
            routes=[RouteCondition(condition="default", next="ending_true")],
        ),

        "act3_bad_ending_route": StoryNode(
            node_id="act3_bad_ending_route",
            act=3,
            scene_name="采桑宫",
            progress=80,
            segments=[
                Segment(speaker="旁白", speaker_type=SpeakerType.NARRATOR,
                        text="没有裴琰的日子，采桑宫越来越冷清。皇帝的翻牌彻底消失了……"),
            ],
            routes=[RouteCondition(condition="default", next="ending_bad")],
        ),

        # ─── 结局 ───
        "ending_true": StoryNode(
            node_id="ending_true",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="温暖",
            is_ending=True,
            ending_type="圆满",
            ending_title="结局·采桑宫春",
            ending_description="温棠封妃，裴琰健康成长，在采桑宫这片小小的净土里，终于有了真正意义上的家。皇帝的目光越来越多地落在采桑宫，不只是因为那碗红豆甜汤，更是因为这里有种久违的安宁。",
            ending_closing="后来裴琰常说，是母妃教会了他，善意不需要回报，但它永远不会白费。",
        ),

        "ending_normal": StoryNode(
            node_id="ending_normal",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="平静",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·岁月静好",
            ending_description="温棠晋了位份，日子稳稳当当地过着。裴琰长大了，偶尔还是会来采桑宫蹭枣花糕。只是那碗红豆甜汤后来皇帝再没提起，仿佛只是寻常一日。",
            ending_closing="温棠后来想，也许平静本身，就是这深宫里最难得的好结局。",
        ),

        "ending_bad": StoryNode(
            node_id="ending_bad",
            act=3,
            scene_name="采桑宫",
            progress=100,
            ambient="萧索",
            is_ending=True,
            ending_type="遗憾",
            ending_title="结局·一盏残灯",
            ending_description="没有裴琰，没有皇帝的眷顾，温棠在采桑宫的灯火越烧越暗。她仍旧做着枣花糕，只是再没有人来吃了。",
            ending_closing="有些错过，一旦发生，就真的过去了。",
        ),
    },
)
